/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionburguermenujavaswing;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author dsantosc04
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private final double IMPORTE_BASICO = 8;
    private final double SUPLEMENTO_SALSA = 0.5;
    private final double DESCUENTO_LOCAL = 0.2;    
    private final double IVA = 0.21;

    private String opcHamburguesa;
    private String opcPan;
    private String opcPatatas;
    private String opcBebida;
    private String opcReparto;
    private boolean opcExtraHamburguesa;
    private boolean opcExtraQueso;
    private boolean opcExtraPatatas;
    private int opcKetchup;
    private int opcMostaza;
    private int opcBarbacoa;
    private int opcThai;
    private double importeTotal;
    private double importeConIVA;
    private double importeImpuestos;
    private int totalPedidosRegistrados;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        totalPedidosRegistrados = 0;
    }

    public void calculoImporteTotal() {
        try {
            importeTotal = 8;
            if (opcHamburguesa.contains("Ternera") || opcHamburguesa.contains("Vegana")) {
                importeTotal += 1;
            }
            if (opcPatatas.contains("Caseras")) {
                importeTotal += 1;
            }
            if (opcExtraHamburguesa) {
                importeTotal += 2;
            }
            if (opcExtraQueso) {
                importeTotal += 0.5;
            }
            if (opcExtraPatatas) {
                importeTotal += 1;
            }
            
            if (opcReparto.contains("Local")) {
                importeTotal = importeTotal - (importeTotal*DESCUENTO_LOCAL);
            }
            
            importeTotal += (opcKetchup*SUPLEMENTO_SALSA);
            importeTotal += (opcMostaza*SUPLEMENTO_SALSA);
            importeTotal += (opcBarbacoa*SUPLEMENTO_SALSA);
            importeTotal += (opcThai*SUPLEMENTO_SALSA);
            
            importeConIVA = importeTotal*IVA;
            importeImpuestos = importeTotal + importeConIVA;
            this.jTextFieldPrecio.setText(String.valueOf(importeTotal));
            this.jTextFieldIVA.setText(String.valueOf(importeConIVA));
            this.jTextFieldPVP.setText(String.valueOf(importeImpuestos));
        } catch (NullPointerException e) {
            this.jTextFieldPrecio.setText("");
        }

    }

    public void recogerDatosUsuario() {
        try {
            opcHamburguesa = this.buttonGroupHamburguesa.getSelection().getActionCommand();
            opcPan = this.buttonGroupPan.getSelection().getActionCommand();
            opcPatatas = this.buttonGroupPatatas.getSelection().getActionCommand();
            opcBebida = this.buttonGroupBebida.getSelection().getActionCommand();
            opcReparto = this.buttonGroupReparto.getSelection().getActionCommand();
            opcKetchup = Integer.parseInt(this.jSpinnerKetchup.getValue().toString());
            opcMostaza = Integer.parseInt(this.jSpinnerMostaza.getValue().toString());
            opcBarbacoa = Integer.parseInt(this.jSpinnerBarbacoa.getValue().toString());
            opcThai = Integer.parseInt(this.jSpinnerThai.getValue().toString());
            opcExtraHamburguesa = this.jCheckBoxHamburguesa.isSelected();
            opcExtraPatatas = this.jCheckBoxExtraPatatas.isSelected();
            opcExtraQueso = this.jCheckBoxExtraQueso.isSelected();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Elige una de las opciones obligatorias del menú", "Error datos", JOptionPane.ERROR_MESSAGE);
            this.jTextFieldPrecio.setText("");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPan = new javax.swing.ButtonGroup();
        buttonGroupPatatas = new javax.swing.ButtonGroup();
        buttonGroupHamburguesa = new javax.swing.ButtonGroup();
        buttonGroupBebida = new javax.swing.ButtonGroup();
        buttonGroupExtra = new javax.swing.ButtonGroup();
        buttonGroupReparto = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSpinnerKetchup = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        jSpinnerBarbacoa = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jSpinnerMostaza = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        jSpinnerThai = new javax.swing.JSpinner();
        jButtonCalcular = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldIVA = new javax.swing.JTextField();
        jTextFieldPVP = new javax.swing.JTextField();
        jRadioButtonPollo = new javax.swing.JRadioButton();
        jRadioButtonCerdo = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButtonVegana = new javax.swing.JRadioButton();
        jRadioButtonPanNormal = new javax.swing.JRadioButton();
        jRadioButtonPanIntegral = new javax.swing.JRadioButton();
        jRadioButtonPanCenteno = new javax.swing.JRadioButton();
        jRadioButtonCaseras = new javax.swing.JRadioButton();
        jRadioButtonFritas = new javax.swing.JRadioButton();
        jRadioButtonGajo = new javax.swing.JRadioButton();
        jRadioButtonCola = new javax.swing.JRadioButton();
        jRadioButtonNaranja = new javax.swing.JRadioButton();
        jRadioButtonLimón = new javax.swing.JRadioButton();
        jRadioButtonAgua = new javax.swing.JRadioButton();
        jRadioButtonCerveza = new javax.swing.JRadioButton();
        jRadioButtonDomicilio = new javax.swing.JRadioButton();
        jRadioButtonLocal = new javax.swing.JRadioButton();
        jCheckBoxHamburguesa = new javax.swing.JCheckBox();
        jCheckBoxExtraQueso = new javax.swing.JCheckBox();
        jCheckBoxExtraPatatas = new javax.swing.JCheckBox();
        jButtonRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Burguer Menu App");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Menú básico (8 €):");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Hamburguesa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Pan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Patatas");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Bebida");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Opciones extra/adicionales");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Salsas (+0,50€ cada una)");

        jLabel26.setText("Ketchup");

        jLabel27.setText("Barbacoa");

        jLabel28.setText("Mostaza");

        jLabel29.setText("Thai");

        jButtonCalcular.setText("CALCULAR");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabel32.setText("PRECIO");

        jLabel33.setText("IVA (21%)");

        jLabel34.setText("P.V.P");

        buttonGroupHamburguesa.add(jRadioButtonPollo);
        jRadioButtonPollo.setText("Pollo");
        jRadioButtonPollo.setActionCommand("Pollo");
        jRadioButtonPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPolloActionPerformed(evt);
            }
        });

        buttonGroupHamburguesa.add(jRadioButtonCerdo);
        jRadioButtonCerdo.setText("Cerdo");
        jRadioButtonCerdo.setActionCommand("Cerdo");

        buttonGroupHamburguesa.add(jRadioButton1);
        jRadioButton1.setText("Ternera (+1 €)");
        jRadioButton1.setActionCommand("Ternera");

        buttonGroupHamburguesa.add(jRadioButtonVegana);
        jRadioButtonVegana.setText("Vegana (+1€)");
        jRadioButtonVegana.setActionCommand("Vegana");

        buttonGroupPan.add(jRadioButtonPanNormal);
        jRadioButtonPanNormal.setText("Normal");
        jRadioButtonPanNormal.setActionCommand("Normal");

        buttonGroupPan.add(jRadioButtonPanIntegral);
        jRadioButtonPanIntegral.setText("Integral");
        jRadioButtonPanIntegral.setActionCommand("Integral");
        jRadioButtonPanIntegral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPanIntegralActionPerformed(evt);
            }
        });

        buttonGroupPan.add(jRadioButtonPanCenteno);
        jRadioButtonPanCenteno.setText("Centeno");
        jRadioButtonPanCenteno.setActionCommand("Centeno");

        buttonGroupPatatas.add(jRadioButtonCaseras);
        jRadioButtonCaseras.setText("Caseras (+1€)");
        jRadioButtonCaseras.setActionCommand("Caseras");

        buttonGroupPatatas.add(jRadioButtonFritas);
        jRadioButtonFritas.setText("Fritas");
        jRadioButtonFritas.setActionCommand("Fritas");

        buttonGroupPatatas.add(jRadioButtonGajo);
        jRadioButtonGajo.setText("Gajo");
        jRadioButtonGajo.setActionCommand("Gajo");

        buttonGroupBebida.add(jRadioButtonCola);
        jRadioButtonCola.setText("Cola");
        jRadioButtonCola.setActionCommand("Cola");

        buttonGroupBebida.add(jRadioButtonNaranja);
        jRadioButtonNaranja.setText("Naranja");
        jRadioButtonNaranja.setActionCommand("Naranja");

        buttonGroupBebida.add(jRadioButtonLimón);
        jRadioButtonLimón.setText("Limón");
        jRadioButtonLimón.setActionCommand("Limon");

        buttonGroupBebida.add(jRadioButtonAgua);
        jRadioButtonAgua.setText("Agua");
        jRadioButtonAgua.setActionCommand("Agua");

        buttonGroupBebida.add(jRadioButtonCerveza);
        jRadioButtonCerveza.setText("Cerveza");
        jRadioButtonCerveza.setActionCommand("Cerveza");

        buttonGroupReparto.add(jRadioButtonDomicilio);
        jRadioButtonDomicilio.setText("Reparto a domicilio");
        jRadioButtonDomicilio.setActionCommand("Domiclio");

        buttonGroupReparto.add(jRadioButtonLocal);
        jRadioButtonLocal.setText("Recogida en local (-20% dto.)");
        jRadioButtonLocal.setActionCommand("Local");

        jCheckBoxHamburguesa.setText("Hamburguesa doble (+2€)");

        jCheckBoxExtraQueso.setText("Extra de queso (+0,50€)");

        jCheckBoxExtraPatatas.setText("Extra de patatas (+1€)");

        jButtonRegistrar.setText("<html> Registar <br> pedido </html>");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel4)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonPollo)
                            .addComponent(jRadioButtonCerdo)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButtonVegana))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonPanNormal)
                            .addComponent(jRadioButtonPanIntegral)
                            .addComponent(jRadioButtonPanCenteno))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonFritas)
                            .addComponent(jRadioButtonGajo)
                            .addComponent(jRadioButtonCaseras)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jRadioButtonCola)
                        .addGap(23, 23, 23)
                        .addComponent(jRadioButtonNaranja)
                        .addGap(27, 27, 27)
                        .addComponent(jRadioButtonLimón)
                        .addGap(27, 27, 27)
                        .addComponent(jRadioButtonAgua)
                        .addGap(19, 19, 19)
                        .addComponent(jRadioButtonCerveza))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jRadioButtonDomicilio)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButtonLocal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jTextFieldIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jTextFieldPVP, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel32)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel33))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jButtonCalcular)))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxExtraPatatas)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel27)
                                .addGap(5, 5, 5)
                                .addComponent(jSpinnerBarbacoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel29)
                                .addGap(30, 30, 30)
                                .addComponent(jSpinnerThai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxHamburguesa)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxExtraQueso)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel26)
                                .addGap(11, 11, 11)
                                .addComponent(jSpinnerKetchup, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel28)
                                .addGap(10, 10, 10)
                                .addComponent(jSpinnerMostaza, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonPollo)
                        .addGap(3, 3, 3)
                        .addComponent(jRadioButtonCerdo)
                        .addGap(0, 0, 0)
                        .addComponent(jRadioButton1)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButtonVegana))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonPanNormal)
                                .addGap(7, 7, 7)
                                .addComponent(jRadioButtonPanIntegral)
                                .addGap(7, 7, 7)
                                .addComponent(jRadioButtonPanCenteno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonFritas)
                                .addGap(7, 7, 7)
                                .addComponent(jRadioButtonGajo)
                                .addGap(7, 7, 7)
                                .addComponent(jRadioButtonCaseras)))))
                .addGap(7, 7, 7)
                .addComponent(jLabel15)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCola)
                    .addComponent(jRadioButtonNaranja)
                    .addComponent(jRadioButtonLimón)
                    .addComponent(jRadioButtonAgua)
                    .addComponent(jRadioButtonCerveza))
                .addGap(7, 7, 7)
                .addComponent(jLabel21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxHamburguesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerKetchup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerMostaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBoxExtraQueso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBoxExtraPatatas))
                    .addComponent(jSpinnerBarbacoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonDomicilio)
                    .addComponent(jRadioButtonLocal))
                .addGap(17, 17, 17)
                .addComponent(jButtonCalcular)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonPanIntegralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPanIntegralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPanIntegralActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        recogerDatosUsuario();
        calculoImporteTotal();
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jRadioButtonPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPolloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPolloActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        totalPedidosRegistrados++;
        try {
            FileWriter fw = new FileWriter("registro-pedidos.txt", true);
            PrintWriter pw = new PrintWriter(fw);
            String cadena = "Pedido: "+totalPedidosRegistrados+".Importe: "+String.valueOf(importeImpuestos);
            pw.println(cadena);
            pw.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupBebida;
    private javax.swing.ButtonGroup buttonGroupExtra;
    private javax.swing.ButtonGroup buttonGroupHamburguesa;
    private javax.swing.ButtonGroup buttonGroupPan;
    private javax.swing.ButtonGroup buttonGroupPatatas;
    private javax.swing.ButtonGroup buttonGroupReparto;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JCheckBox jCheckBoxExtraPatatas;
    private javax.swing.JCheckBox jCheckBoxExtraQueso;
    private javax.swing.JCheckBox jCheckBoxHamburguesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonAgua;
    private javax.swing.JRadioButton jRadioButtonCaseras;
    private javax.swing.JRadioButton jRadioButtonCerdo;
    private javax.swing.JRadioButton jRadioButtonCerveza;
    private javax.swing.JRadioButton jRadioButtonCola;
    private javax.swing.JRadioButton jRadioButtonDomicilio;
    private javax.swing.JRadioButton jRadioButtonFritas;
    private javax.swing.JRadioButton jRadioButtonGajo;
    private javax.swing.JRadioButton jRadioButtonLimón;
    private javax.swing.JRadioButton jRadioButtonLocal;
    private javax.swing.JRadioButton jRadioButtonNaranja;
    private javax.swing.JRadioButton jRadioButtonPanCenteno;
    private javax.swing.JRadioButton jRadioButtonPanIntegral;
    private javax.swing.JRadioButton jRadioButtonPanNormal;
    private javax.swing.JRadioButton jRadioButtonPollo;
    private javax.swing.JRadioButton jRadioButtonVegana;
    private javax.swing.JSpinner jSpinnerBarbacoa;
    private javax.swing.JSpinner jSpinnerKetchup;
    private javax.swing.JSpinner jSpinnerMostaza;
    private javax.swing.JSpinner jSpinnerThai;
    private javax.swing.JTextField jTextFieldIVA;
    private javax.swing.JTextField jTextFieldPVP;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
